version: "3.3"
services:
  nginx:
    restart: always
    container_name: cloud-nginx-prod
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    tty: true
    ports:
      - "4999:80"
    depends_on:
      - db
      - api
      - redis
  db:
    restart: always
    container_name: cloud-db-prod
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db/prod_postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_DBNAME
      - POSTGRES_PASS
      - POSTGRES_USER
      - DEFAULT_COLLATION
      - DEFAULT_CTYPE
      - DEFAULT_ENCODING
      - DEFAULT_USER
      - DEFAULT_PASS
      - DEFAULT_GROUPS
      - DEFAULT_GROUP
    healthcheck:
      test:
        [
          "CMD",
          "export",
          "PGPASSWORD=nielogowacsienategousera",
          "&&",
          "pg_isready",
          "-U",
          "docker",
        ]
      interval: 5s
      timeout: 3s
      retries: 5
  api:
    restart: always
    container_name: cloud-api-prod
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    command: bash -c "./prod_start.sh"
    environment:
      - PYTHONUNBUFFERED
      - FLASK_APP
      - DEFAULT_GROUPS
      - DEFAULT_USER
      - DEFAULT_PASS
      - DEFAULT_GROUP
    depends_on:
      - db
      - redis
  redis:
    restart: always
    container_name: cloud-redis-prod
    image: redis:5.0.6
    volumes:
      - ./docker/db/prod_redis_data:/data
