version: "3.3"
services:
  db:
    container_name: ${CONTAINER_BASENAME}-db
    restart: always
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    ports:
      - "5000:5432"
    volumes:
      - ./docker/db/postgres_data:/var/lib/postgresql
      - ./docker/db/dumps:/dumps
    environment:
      - POSTGRES_DBNAME
      - POSTGRES_PASS
      - POSTGRES_USER
      - DEFAULT_COLLATION
      - DEFAULT_CTYPE
      - DEFAULT_ENCODING
      - DEFAULT_USER
      - DEFAULT_PASS
      - DEFAULT_GROUPS
      - DEFAULT_GROUP
  api:
    container_name: ${CONTAINER_BASENAME}-api
    restart: always
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    command: bash -c "./start.sh"
    tty: true
    ports:
      - "5001:5001"
    volumes:
      - ./api:/api
    environment:
      - PYTHONUNBUFFERED
      - FLASK_APP
      - DEFAULT_GROUPS
      - DEFAULT_USER
      - DEFAULT_PASS
      - DEFAULT_GROUP
      - CONTAINER_BASENAME
      - APP_DEV_DB_PORT
      - APP_DEV_HOST_URL
      - CONFIG=development
    depends_on:
      - db
      - redis
  redis:
    container_name: ${CONTAINER_BASENAME}-redis
    image: redis:5.0.6
    volumes:
      - ./docker/db/redis_data:/data
