version: "3.3"
services:
  db:
    container_name: cloud-db
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    ports:
      - "5000:5432"
    volumes:
      - ./docker/db/postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_DBNAME
      - DEFAULT_COLLATION
      - DEFAULT_CTYPE
      - DEFAULT_ENCODING
      - POSTGRES_PASS
      - DEFAULT_USER
      - DEFAULT_PASS
      - DEFAULT_GROUPS
  api:
    container_name: cloud-api
    restart: always
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    command: bash -c "./start.sh"
    tty: true
    ports:
      - "5001:5001"
    volumes:
      - ./api:/api
    environment:
      - PYTHONUNBUFFERED
      - FLASK_APP
      - DEFAULT_GROUPS
      - DEFAULT_USER
      - DEFAULT_PASS
    depends_on:
      - db
      - redis
  redis:
    container_name: cloud-redis
    image: redis:5.0.6
    volumes:
      - ./docker/db/redis_data:/data
