Get settings
---
tags:
  - Analysis
summary: Get analysis settings
produces:
  - application/json
parameters:
  - name: token
    in: query
    description: Token
    required: false
    type: string
responses:
  200:
    schema:
      type: object
      properties:
        settings:
          type: object
          properties:
            pn:
              type: string
            pk:
              type: string
  403:
    description: Token required
    schema:
      type: object
      properties:
        error:
          type: string
          example: "token required"
