Add column
---
tags:
  - Layers
summary: Add column to layer
produces:
  - application/json
parameters:
  - name: lid
    in: path
    description: Layer ID
    required: true
    type: string
  - in: body
    name: body
    required: true
    schema:
      type: object
      properties:
        column_name:
          type: string
          example: "test"
          required: false
        column_type:
          type: string
          required: false
        layer_name:
          type: string
          required: false
  - name: token
    in: query
    description: Token
    required: false
    type: string
responses:
  200:
    description: GeoJSON
    schema:
      type: object
      properties:
        id:
          type: string
        name:
          type: object
        columns:
          type: array
  403:
    description: Token required
    schema:
      type: object
      properties:
        error:
          type: string
          example: "token required"
